### ISSUE TITLE
Don't show "Clear records" as the first option

### ISSUE THREAD

**Issue by Chaoscontrol** [Jack251970/Flow.Launcher.Plugin.ClipboardPlus#2]
This is more an improvement than a bug. 

When opening Clipboard+, it seems it always defaults to showing "Clear records" as the first option, which makes it dangerous to clear all your clipboard by mistake. 

I think the first option should always be the most recent result copied, which is most likely the one you want to paste again. "Clear records" should show up last in the list imo, unless you start searching with the query. 

https://xfiles.s-ul.eu/NiWzomIU

**Comment by Jack251970** [comment]
Support for changing action items on top or bottom in version 1.1.1

**Comment by Chaoscontrol** [comment]
Sorry @Jack251970 but I don't understand what was added with the update. 

![image](https://github.com/user-attachments/assets/9b39f9be-cc75-4f39-8d3c-4330dc2cf5eb)

All I see is that now there are 2 results to clear/clean the clipboard or records. Not sure what is the difference or the utility of clearing the clipboard. 

Plus what do you mean with changing action items top or bottom? If you mean the context option to pin or set to top, that doesn't solve the problem, as you cannot pin "all results" to the top so that "Clean results" sits at the bottom. 
![image](https://github.com/user-attachments/assets/8d4cf9e5-40fd-4ccd-b7c0-1079c5a95776)

Maybe I'm missing something. 
Thanks!

**Comment by Jack251970** [comment]
Try "Action top" option in setting panel

**Comment by Chaoscontrol** [comment]
> Try "Action top" option in setting panel

Oh, I missed that! Thanks! It works!

Although it seems to work the opposite way. When checked, it places the Clear actions at the top. Or maybe keep it this way just update the description saying "Place clear actions to the top of the list". I think that's more descriptive. 

![image](https://github.com/user-attachments/assets/757ebef0-9eed-47d0-8e37-e8eaa9bb87fb)
![image](https://github.com/user-attachments/assets/cee5c527-93fd-4ec4-99b8-6f96dffe9e08)

But anyway, it works perfect, thank you very much!

**Comment by Jack251970** [comment]
Year, I do think "Action top" can be a little hard to understand. So, I change it to "Set the action options (e.g., Clean clipboard) as topmost / bottommost in the query", which I think is more descriptive.
