### ISSUE TITLE
Image caching not working

### ISSUE THREAD

**Issue by xsidexpt** [Jack251970/Flow.Launcher.Plugin.ClipboardPlus#3]
Not sure why, but I can't get image caching to work at all.
If I copy an image on the browser, that entry does not show up at all on the clipboard. And if I copy a local image it will just show on the clipboard as the path of the image with no preview.
Already tried playing around with the “cache images” toggle and the "keep image" toggle to no avail.
I also note that no images are getting copied to the cached images directory.

**Comment by Jack251970** [comment]
Sorry I cannot fully understand this. The latest version has made stability improvements that may resolve the issue.

**Comment by Chaoscontrol** [comment]
Here are my settings in case it helps. 
For me it works perfect. As soon as I copy an image, it appears in the cache folder. 
![image](https://github.com/user-attachments/assets/d9d23d3e-883e-4f5a-bd29-2208387c67be)
![image](https://github.com/user-attachments/assets/9ab733d6-726d-4d20-a510-ed5ffe0badf1)

**Comment by xsidexpt** [comment]
I could have sworn this behaviour was different in the past and the cache worked every time.
For instance, if I clip copy on a local .jpg file this is what shows up 
![image](https://github.com/user-attachments/assets/d650c533-0dc7-455e-9d0e-5490a24271ad)
and if I click copy on an image in the browser that not represented at all in the clipboard history.

**Comment by Chaoscontrol** [comment]
So weird. It does perfectly either from browser or local to me. :S Maybe reinstall the plugin? No clue tbh.

**Comment by xsidexpt** [comment]
I have tried to reinstall and install again, tried an older version of flow launcher and tried a portable installation.
Nothing made a difference.
Also, I could have sworn that there were thumbnails for the images in the past?
All this may have coincided with Windows 11 updating to the 24h2 update.
This same exact behaviour happen with other clipboard extensions available in the flow launcher plugin store.

**Comment by Chaoscontrol** [comment]
I don't recall thumbnails before. They show on the right panel, but not on the list.

**Comment by xsidexpt** [comment]
Previous to this week I was using ClipboardR but since that also got this weird behaviour I thought I could try the other options to see if they also share the same issues, and sure enough they do!

**Comment by Chaoscontrol** [comment]
Clipboard+ is a fork from ClipboardR (which is not maintained anymore AFAIK), but has been improved since.

**Comment by xsidexpt** [comment]
That was part of the reason for the switch.
Are you by any chance running Windows 11 24H2? 
It would not surprise me if this was somehow Microsoft's fault 🙃

**Comment by Chaoscontrol** [comment]
Yep, 24H2. For a few months already. Really no clue what might be messing with yours.

**Comment by xsidexpt** [comment]
Dammit... well, it was worth the shot.
Just to be 100% sure, we are talking about the exact same thing. If you click "copy image" in any browser, that image shows up in your clipboard, right?
And if you click copy in any image file on your local drive, that also shows there with a preview?
I have some images show up, particularly if I take a screenshot, for example.

**Comment by Chaoscontrol** [comment]
Here you go: https://xfiles.s-ul.eu/tcXSHBnl

1. When copying from browser, it copies fine with thumbnail. 
2. When copying file from desktop, it copies the path. 
3. When copying the same file while open, it copies the image with thumbnail.

**Comment by xsidexpt** [comment]
Thanks for the effort!
It might just be one of those random behaviours that will push me over the edge to get a clean install of windows on my machine.
Oh, well…
If I randomly stumble across the answer, I will let you know, might be something useful/intersting.

**Comment by xsidexpt** [comment]
Hey! I have since fixed my issue, and it was indeed something on the windows side of things.
I have however found a correlation between flow launcher and your plugin.
Basically no matter the settings in the plug in itself for image caching, database encryption, or anything else, there is a severe ram usage increase for the flow launcher process when copying images in a browser.
The behaviour I tried was the following, copying a 25mb.jpg file creates a big jump from around 110mb of ram usage to around 900. The more images I copy, the larger the ram usage gets, and it will not drop back down until flow launcher is restarted.
If I copy multiple images in a row, flow launcher will hang, and I am unable to open the search bar until it finishes processing.

This same behaviour is seen with the ClipboardR plugin, which does make sense given the current base for your plugin.

I don't think this is expected behaviour, and it completely flew under my radar for months when I was wondering why I was getting random system halts for no apparent reason.

(Also previously I pointed out that I remember having thumbnails for copied images in the clipboard, but that was from ClipboardR that does those thumbnails by default)

I am open to test a fix for this and help you make sure this is properly addressed.
For reference, the performance is slow on my system with a Gen 4 NVMe SSD and Ryzen 5900x.

**Comment by Jack251970** [comment]
Have you opened the preview panel? The images should be stored for possible preview usage.

**Comment by xsidexpt** [comment]
> Have you opened the preview panel? The images should be stored for possible preview usage.

Maybe I should have migrated this to a different issue, I chose to keep it here since there was a bit of context surrounding my setup, but this latest post is a completely different thing.
The initial issue is addressed and is no longer a problem.
The high ram usage however and the full system hangs are the current issue.
I can get ram usage of multiple Gb that only goes away when I restart flow launcher and the records are cleared from the clipboard.

**Comment by Jack251970** [comment]
Could you open a new issue and share more details for this?
