### ISSUE TITLE
Click action doesn't work

### ISSUE THREAD

**Issue by yozhic** [Jack251970/Flow.Launcher.Plugin.ClipboardPlus#5]
**Reproduce**:
Call the plugin, select any of the data lines by click LMB or press <kbd>Enter</kbd>.

**Expected**:  
Data is copied to the clipboard.
 
**Actual**:  
Nothing's happening. Data is not copied to the clipboard (and no copy notification message is displayed).  
You can only copy data to the clipboard by opening the additional plugin's menu and selecting the `Copy as plain text` command.

It seems to be a regression of version 1.1.5, because in the previous 1.1.4 these actions worked fine.

I'm on the Windows 11 Enterprise 23H2 [22631.4169], Flow Launcher 1.19.4, Clipboard+ 1.1.5.

Thanks in advance.

**Comment by yozhic** [comment]
So, I had to roll back to the previous version 1.1.4 where Click action works.

**Comment by Jack251970** [comment]
Sorry to bring this annoying issue. Now fixed in 1.1.6.
