### ISSUE TITLE
"Clear records" action not working

### ISSUE THREAD

**Issue by Chaoscontrol** [Jack251970/Flow.Launcher.Plugin.ClipboardPlus#6]
The "Clear records" action doesn't seem to be working. After using it, I still can see all the clipboard history in Flow, and I don't think it's clearing the db either (not sure about this, but the db file size doesn't change after doing it. 

[Video example](https://xfiles.s-ul.eu/qt0jwths)

**Comment by Jack251970** [comment]
Sorry for any inconvenience. Currently busy on other things. Will check it this weekend.

**Comment by Chaoscontrol** [comment]
Yeah, no problem, it's not a big deal.

**Comment by Jack251970** [comment]
Already fix in 1.1.8.
